### ISSUE TITLE
cause: java.lang.ClassCastException: com.jaycekon.dubbo.service.impl.UserServiceImpl cannot be cast to com.jaycekon.dubbo.service.impl.UserServiceImpl com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote proxy method inserUser to 

### ISSUE THREAD

**Issue by fengmnegchang** [guangjingfenggmail/springqianbailu#1]
was an unexpected error (type=Internal Server Error, status=500).
Failed to invoke remote method: inserUser, provider: dubbo://127.0.0.1:20880/com.jaycekon.dubbo.service.UserService?application=consumer&dubbo=2.5.3&interface=com.jaycekon.dubbo.service.UserService&methods=inserUser,selectUser&pid=4521&side=consumer&timestamp=1545285226696, cause: com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote proxy method inserUser to registry://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=provider&dubbo=2.5.3&export=dubbo%3A%2F%2F192.168.12.204%3A20880%2Fcom.jaycekon.dubbo.service.UserService%3Fanyhost%3Dtrue%26application%3Dprovider%26dubbo%3D2.5.3%26interface%3Dcom.jaycekon.dubbo.service.UserService%26methods%3DinserUser%2CselectUser%26pid%3D4519%26side%3Dprovider%26timestamp%3D1545285222312&pid=4519&registry=zookeeper&timestamp=1545285222305, cause: java.lang.ClassCastException: com.jaycekon.dubbo.service.impl.UserServiceImpl cannot be cast to com.jaycekon.dubbo.service.impl.UserServiceImpl com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote proxy method inserUser to registry://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=provider&dubbo=2.5.3&export=dubbo%3A%2F%2F192.168.12.204%3A20880%2Fcom.jaycekon.dubbo.service.UserService%3Fanyhost%3Dtrue%26application%3Dprovider%26dubbo%3D2.5.3%26interface%3Dcom.jaycekon.dubbo.service.UserService%26methods%3DinserUser%2CselectUser%26pid%3D4519%26side%3Dprovider%26timestamp%3D1545285222312&pid=4519&registry=zookeeper&timestamp=1545285222305, cause: java.lang.ClassCastException: com.jaycekon.dubbo.service.impl.UserServiceImpl cannot be cast to com.jaycekon.dubbo.service.impl.UserServiceImpl at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76) at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) at

**Comment by fengmnegchang** [comment]
解决：删除
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
